### ISSUE TITLE
assets中的sql是否有缺失？

### ISSUE THREAD

**Issue by HaiZhiLanGe** [boluokk/hr-system#1]
2024-03-16 12:58:11 |ERROR |http-nio-44565-exec-10 |GlobalExceptionCustom.java:91 |org.boluo.hr.exception.GlobalExceptionCustom |其他异常: class org.springframework.jdbc.BadSqlGrammarException + 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE hourlySequence AS (
        SELECT
        DATE_ADD(CURDATE(), INTERVA' at line 1
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE hourlySequence AS (
        SELECT
        DATE_ADD(CURDATE(), INTERVA' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE hourlySequence AS (
        SELECT
        DATE_ADD(CURDATE(), INTERVA' at line 1
2024-03-16 13:00:00 |ERROR |MessageBroker-5 |TaskUtils.java:95 |org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler |Unexpected error occurred in scheduled task

看mapper.xml是取了hourlySequence表里的数据，项目里已有的hr_no_foreign_key.sql没建这张表，请问下应该怎么办呢？是不是得麻烦您更新下

**Comment by boluokk** [comment]
把mysql版本换成8.0及或以上

**Comment by HaiZhiLanGe** [comment]
> 把mysql版本换成8.0及或以上

感谢大佬回复，对8.0语法了解不多，看到缺表就来提issue了，麻烦了。
